services:
  postgres:
    image: postgres:17-alpine
    container_name: venli-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: venli_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: venli-backend-dev
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
      DB_HOST: postgres
      USING_DOCKER: "true"
    volumes:
      - .:/app
      - mix_deps:/app/deps
      - mix_build:/app/_build
    depends_on:
      - postgres
    command: mix phx.server

volumes:
  dbdata:
  mix_deps:
  mix_build:
