import Config

# Configure your database
config :venli_core, VenliCore.Repo,
  username: "root",
  password: "toor",
  # DB_HOST for when running with docker
  hostname: System.get_env("DB_HOST") || "localhost",
  database: "venli_db",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :venli_core, VenliCoreWeb.Endpoint,
  # loopback: 127.0.0.1 if running without docker, if running with docker, 0.0.0.0
  http: [
    ip: if(System.get_env("USING_DOCKER") == "true", do: {0, 0, 0, 0}, else: {127, 0, 0, 1}),
    port: 4000
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "19Bp6Q/lwZ4grDJo9LWCOfjE65Me2egYEOMMoxo3pFc/8fdUUNCkVR5b/l5w4BaD",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :venli_core, dev_routes: true

# Configure frontend URL for dev
config :venli_core,
  frontend_url: "http://localhost:3000"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Import environment specific config. 
# This overrides the configuration defined above.
import_config "dev.secret.exs"
